"""updated the foods list

Revision ID: abf37459e115
Revises: b3361d31d6e5
Create Date: 2025-03-11 10:27:27.842605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abf37459e115'
down_revision = 'b3361d31d6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###